---
- name: Create homebridge Container
  docker_container:
    name: "homebridge"
    image: "oznu/homebridge:latest"
    #networks:
    #  - name: "{{ IPNET_NAME }}"
    #    ipv4_address: "{{ IP_IP }}"
    networks_cli_compatible: yes
    #published_ports: "85:80"
    #exposed_ports: "80:80"
    network_mode: host
    env:
      TZ: "Africa/Johannesburg"
      ENABLE_AVAHI: "0"
    volumes:
      - "homebridge:/homebridge"
...