---
- name: Copy Admin Config to Home Dir
  copy:
    remote_src: yes
    src: /etc/kubernetes/admin.conf
    dest: /home/ubuntu/.kube/config

- name: Create CNI Weave Network
  shell: kubectl apply -f "https://cloud.weave.works/k8s/net?k8s-version=$(kubectl version | base64 | tr -d '\n')"

- name: Kubeadm reset
  shell: kubeadm reset

- name: Kubeadm init again
  shell: kubeadm init