---
- name: Install Samba
  apt:
    name: "{{ packages }}"
    update_cache: yes
    state: latest
  vars:
    packages:
    - samba

#- name: Create User admin
#  user:
#    name: admin
#    password: '{{ sambapass }}'
#    groups:
#      - www-data
#    state: present
#    system: yes
#    shell: /sbin/nologin
#    createhome: no

# This doesnt / didnt work???
#- name: Create Samba User admin
#  shell: "printf '{{ sambapass }}\n{{ sambapass }}\n' | smbpasswd -a {{ sambauser }}"
#  failed_when: false
#  changed_when: false

- name: Configure smb.conf
  blockinfile:
    path: /etc/samba/smb.conf
    block: |
      [data]
         comment = Data
         path = /media/data/share
         read only = no
         create mask = 0770
         directory mask = 0771
         guest ok = yes
         public = yes
         force user = ubuntu
         force group = ubuntu

- name: Restart Samba Service
  systemd:
    state: restarted
    name: smbd
...
