---
- name: READARR container
  docker_container:
    name: "{{ TORRENT_READARR_NAME }}"
    image: "{{ TORRENT_READARR_IMAGE }}"
    restart_policy: unless-stopped
    networks:
     - name: "{{ TORRENT_NET_NAME }}"
       ipv4_address: "{{ TORRENT_READARR_IP }}"
    published_ports: "{{ TORRENT_READARR_PORT }}:8787"
    volumes:
      - "{{ TORRENT_READARR_NAME }}:/config"
      - "{{ DATA_LOCATION_BOOKS }}:/books"
      - "{{ DATA_LOCATION_QDOWNLOADS }}:/downloads"
    env:
      PUID: "{{ PUID }}"
      PGID: "{{ PGID }}"
      TZ: "{{ TIMEZONE }}"
...