---
- name: Create LANCACHE-DNS Container
  docker_container:
    name: "lancache-dns"
    image: "jrcichra/lancachenet-lancache-dns:latest"
    restart_policy: unless-stopped
    networks_cli_compatible: yes
    published_ports: 
      - "192.168.19.110:53:53/udp"
    volumes:
      - "/mnt/data/cache/data:/data/cache"
      - "/mnt/data/cache/logs:/data/logs"
    env:
      UPSTREAM_DNS="1.1.1.3; 1.0.0.3"
      LANCACHE_IP="192.168.19.110"
      USE_GENERIC_CACHE=true

- name: Create MONOLITHIC Container
  docker_container:
    name: "monolithic"
    image: "jrcichra/lancachenet-monolithic:latest"
    restart_policy: unless-stopped
    networks_cli_compatible: yes
    published_ports: 
      - "80:80"
      - "443:443"
    volumes:
      - "/mnt/data/cache/data:/data/cache"
      - "/mnt/data/cache/logs:/data/logs"
    env:
      UPSTREAM_DNS="1.1.1.3 1.0.0.3"
      CACHE_MEM_SIZE="300m"
      CACHE_DISK_SIZE="1000000m"
      CACHE_MAX_AGE="3560d"
...
