---
- name: Create NGINX Container
  docker_container:
    name: "{{ NGINX_NAME }}"
    image: "{{ NGINX_IMAGE }}"
    #networks:
    #  - name: "{{ _NAME }}"
    #    ipv4_address: "{{ FFDB_IP }}"
    network_mode: host
    networks_cli_compatible: yes
    published_ports: 
      - "80:80"
      - "443:443"
    restart_policy: unless-stopped
    volumes:
      - "/etc/nginx:/config"
      - "/etc/letsencrypt:/etc/letsencrypt"
...