---
### Create the network - to only publish the app and expose db, etc.
- name: Create Docker Network
  docker_network:
    name: "{{ DNS_NAME }}"
    ipam_config:
      - subnet: "{{ DNS_SUBNET }}"
        gateway: "{{ DNS_GW }}"
        iprange: "{{ DNS_SUBNET }}"

- name: PIHOLE container
  docker_container:
    name: "{{ PIHOLE_NAME }}"
    image: "{{ PIHOLE_IMAGE }}"
    networks:
      - name: "{{ DNS_NAME }}"
        ipv4_address: "{{ PIHOLE_IP }}"
    restart_policy: "always"
    exposed_ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
     # - "81:81:tcp"
    published_ports:
      - "81:81/tcp"
    volumes:
      - "/etc/pihole/:/etc/pihole/"
      - "/etc/dnsmasq.d/:/etc/dnsmasq.d/"
    env:
      TZ: "{{ TIMEZONE }}"
      WEBPASSWORD: "{{ PIHOLE_PASSWORD }}"
      ServerIP: "{{ PIHOLE_IP }}"
      DNS1: "{{ DNS1 }}"
      DNS2: "{{ DNS2 }}"
      DNSMASQ_LISTENING: all
      WEB_PORT: "81"
    capabilities:
      - NET_ADMIN

- name: Create LANCACHE Container
  docker_container:
    name: "lancache"
    image: "lancachenet/lancache-dns:latest"
    networks:
      - name: "{{ DNS_NAME }}"
        ipv4_address: "{{ LANCACHE_IP }}"
    restart_policy: always
    networks_cli_compatible: yes
    published_ports: 
      - "53:53/udp"
    volumes:
      - "{{ VOLUME }}/cache/data:/data/cache"
      - "{{ VOLUME }}/cache/logs:/data/logs"
    env:
      UPSTREAM_DNS="{{ PIHOLE_IP }}"
      LANCACHE_IP="{{ LANCACHE_IP_OF_HOST }}"
      USE_GENERIC_CACHE=true

- name: Create MONOLITHIC Container
  docker_container:
    name: "monolithic"
    image: "lancachenet/monolithic:latest"
    networks:
      - name: "{{ DNS_NAME }}"
        ipv4_address: "{{ MONOLITHIC_IP }}"
    restart_policy: always
    networks_cli_compatible: yes
    published_ports: 
      - "80:80"
      - "443:443"
    volumes:
      - "{{ VOLUME }}/cache/data:/data/cache"
      - "{{ VOLUME }}/cache/logs:/data/logs"
    env:
      UPSTREAM_DNS="{{ PIHOLE_IP }}"
      CACHE_MEM_SIZE="300m"
      CACHE_DISK_SIZE="1000000m"
      CACHE_MAX_AGE="3560d"
...
