---
- name: Stop Ark
  command: arkmanager stop
  register: res
  failed_when: false
  changed_when: false

- name: Configure ArkManager
  template:
    src: templates/arkmanager.cfg.j2
    dest: /etc/arkmanager/arkmanager.cfg

- name: Configure ArkManager Instance
  template:
    src: templates/main.cfg.j2
    dest: /etc/arkmanager/instances/main.cfg

- name: Configure Game.ini
  synchronize:
    src: templates/Game.ini
    dest: /home/steam/ARK/ShooterGame/Saved/Config/LinuxServer/Game.ini

- name: Configure GameUserSettings.ini
  template:
    src: templates/GameUserSettings.ini.j2
    dest: /home/steam/ARK/ShooterGame/Saved/Config/LinuxServer/GameUserSettings.ini

- name: Install Mods
  command: arkmanager installmods
  failed_when: false
  changed_when: false

- name: Start Ark
  command: arkmanager start
  register: res
  failed_when: false
  changed_when: false
...
