---
- name: PLEX container
  docker_container:
    name: "{{ TORRENT_PLEX_NAME }}"
    image: "{{ TORRENT_PLEX_IMAGE }}"
    #restart_policy: "no"
    restart_policy: unless-stopped
    network_mode: host
    #networks:
    #  - name: "{{ TORRENT_NET_NAME }}"
    #    ipv4_address: "{{ TORRENT_PLEX_IP }}"
    #published_ports: "{{ TORRENT_PLEX_PORT }}:32400"
    #purge_networks: yes
    #networks_cli_compatible: no
    volumes:
      - "{{ TORRENT_PLEX_NAME }}:/config"
      - "{{ DATA_LOCATION_MOVIES }}:/movies"
      - "{{ DATA_LOCATION_SERIES }}:/series"
      - "{{ DATA_LOCATION_PHOTOS }}:/photos"
      - "{{ DATA_LOCATION_TRAINING }}:/training"
      - "{{ DATA_LOCATION_BOOKS }}:/books"
    env:
      PUID: "{{ PUID }}"
      PGID: "{{ PGID }}"
      VERSION: "{{ TORRENT_PLEX_VERSION }}"
      PLEX_CLAIM: "{{ TORRENT_PLEX_CLAIM }}"
...


# To do:
# explained here: https://www.techjunkie.com/how-to-install-plugins-plex/
# download:
# https://github.com/ukdtom/WebTools.bundle/releases/tag/2.4.1
# then copy WebTools.bundle to volumes/plex/_data/Library/Application Support/Plex Media Server/Plug-ins
# reboot server
#  chown -R ubuntu:ubuntu WebTools.bundle/
# This just gives you ability to download plugins manually in a nice and easy way -
# we could always just download whatever version of a plugin and add to this playbook
# both are a good idea
# after adding plugin via WebTools, it appears that you need to restart docker container
